#!/public/home/lijunhao/soft/python3_amb22
import argparse
import sys
import re

def judge_pdb_element(line):
    message = ("\nPlease add the element to the last column of the PDB file!\n"
               "This could be done manually or generated by PyMOL\n\n")
    if len(line) < 67 or line[67:].strip() == '':
        sys.stdout.write(message)
        sys.stdout.flush()
        sys.exit(1)

def gau_template(mol, chg, mul, stage, func, basis, cpus, mems):
    if stage in ["HEAD1","HEAD2"]: # just_opt | esp with pre_opt
        msg = f"""%chk={mol}.chk
%nprocshared={cpus}
%mem={mems}GB
#p opt {func}/{basis} nosymm 

NO TITLE

{chg} {mul}
"""
    elif stage == "HEAD3": # esp without pre_opt
        msg = f"""%chk={mol}.chk
%nprocshared={cpus}
%mem={mems}GB
#p {func}/{basis} pop=mk IOp(6/33=2,6/50=1)
nosymm

NO TITLE

{chg} {mul}
"""
    elif stage == 'END1': # just_opt
        msg = "\n\n\n\n\n"
    elif stage == 'END2': # esp with pre_opt
        # Link1 job for a subsequent single point calculation
        msg = f"""\n--link1--
%chk={mol}.chk
%nprocshared={cpus}
%mem={mems}GB
#p {func}/{basis} pop=mk IOp(6/33=2,6/50=1)
geom=check guess=read nosymm

NO TITLE

{chg} {mul}
results_{mol}.esp



"""
    elif stage == 'END3': # esp without pre_opt
        # Trailing part (if needed)
        msg = f"""\n{mol}.esp\n\n\n\n"""

    return msg

def gen_gau_inp(pdb_file, charge, multip, func, basis, pre_opt, just_opt, cpus, mems):
    mol = pdb_file.split('/')[-1].split('.')[0]
    com_file = f"{mol}.com"
    num = 0
    with open(com_file, 'w') as out:
        for line in open(pdb_file, 'r'):
            if not (line.startswith("ATOM") or line.startswith("HETA")):
                continue
            judge_pdb_element(line)
            num += 1
            # Get the element from the last column (extracted using regex)
            elemt = ''.join(re.split(r'[^A-Za-z]', line.split()[-1]))
            # Replace underscores in atom names if needed
            atom = line[11:17].strip().replace('_', 'd')
            # Residue name and number (can be used for comments if desired)
            resname = line[17:21].strip()
            resid = line[22:26].strip()
            xyz = line[27:55]
            coor = f"{elemt:<10}{xyz:>40}\n"
            if num == 1:
                if just_opt:
                    out.write(gau_template(mol, charge, multip, 'HEAD1', func, basis, cpus, mems))
                elif pre_opt:
                    out.write(gau_template(mol, charge, multip, 'HEAD2', 'b3lyp', '6-31g(d,p)', cpus, mems))
                else:
                    out.write(gau_template(mol, charge, multip, 'HEAD3', func, basis, cpus, mems))
            out.write(coor)
        if just_opt:
            out.write(gau_template(mol, charge, multip, 'END1', func, basis, cpus, mems))
        elif pre_opt:
            out.write(gau_template(mol, charge, multip, 'END2', func, basis, cpus, mems))
        else:
            out.write(gau_template(mol, charge, multip, 'END3', func, basis, cpus, mems))

    sys.stdout.write(f"\nDone! Number of atoms: {num}\n\n")
    sys.stdout.flush()

def main():
    parser = argparse.ArgumentParser(
        description="Process a ligand PDB (from pymol) and generate a Gaussian input (.com) file."
    )
    parser.add_argument("-pdb", required=True, help="Input ligand PDB file")
    parser.add_argument("-charge", required=True, help="Molecular charge")
    parser.add_argument("-multip", required=True, help="Multiplicity")
    parser.add_argument("-func", default="hf", help="Functional to use (default: hf)")
    parser.add_argument("-basis", default="aug-cc-pvtz", help="Basis set to use (default: aug-cc-pvtz)")
    parser.add_argument("-pre_opt", action="store_true", 
                        help="Perform geometrical opt before esp fitting")
    parser.add_argument("-just_opt",action="store_true",
                        help="just perform geometry optimization, without esp fitting")
    parser.add_argument("--cpus",default="24",help="Number of processers in com file")
    parser.add_argument("--mems",default="96",help="amount of memory in com file")
    
    args = parser.parse_args()

    gen_gau_inp(args.pdb, args.charge, args.multip, args.func, args.basis, 
                args.pre_opt, args.just_opt, args.cpus, args.mems)

if __name__ == '__main__':
    main()
